version: '3.9'

services:
  docker-nginx:
    image: nginx:1.25.3
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: docker-nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./app:/var/www
    networks:
      - web-network
  docker-php:
#    image: php:8.3-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-php
    volumes:
      - ./app:/var/www
    networks:
      - web-network
networks:
  web-network:
    driver: bridge