version: '3.9'

services:
  docker-nginx:
    image: nginx:1.25.3
    container_name: docker-nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./app:/var/www
    networks:
      - web-network
  docker-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-php
    volumes:
      - ./app:/var/www
    networks:
      - web-network
  mysql:
      image: mysql:8.3.0
      container_name: docker-mysql
      volumes:
        - ./database:/var/lib/mysql
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root_password
      ports:
        - "3306:3306"
      networks:
        - web-network
volumes:
  nginx:
  app:
  database:
networks:
  web-network:
    driver: bridge